// <auto-generated />
namespace DigitalInspection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CannedResponsesHaveLevelsOfConcern_AsString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CannedResponsesHaveLevelsOfConcern_AsString));
        
        string IMigrationMetadata.Id
        {
            get { return "201711200150378_CannedResponsesHaveLevelsOfConcern_AsString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
